### ISSUE TITLE
[Feature Request] Get js-beautify options from VSCode workspace settings

### ISSUE THREAD

**Issue by eastcoastcoder** [thomas-ziirsen/web-component-vs-code-extension#1]
Hello, this extension is working great for webcomponents, there really isn't anything quite like it in the marketplace 👍 
I was wondering if support could be added for reading workspace settings while formatting?

Specifically what I'm trying to do is get my js files to honor my `editor.tabSize` of 2, where js-beautify defaults this to 4. In a different js-beautify extension, they are able to parse the settings like the following method. Maybe this would be a pretty easy lift to incorporate into this extension?

https://github.com/HookyQR/VSCodeBeautify/blob/master/options.js#L38

**Comment by struers-tmz** [comment]
Hi Eastcoastcoder,

I'm happy that you like the extensions, I to use it in my daily work with TypeScript 🍰 

I will have a look at your request, but would defenatly think that it would be easy to implement. I'm a bit busy at work today, but will have a look at it tomorrow most likely and give you an update.

Cheers
Thomas ⚔️

**Comment by thomas-ziirsen** [comment]
Hi again,

I have completed your feature request - but i'm having some SSH issues since i recently wiped my PC. I'll see if i can get it fixed tomorrow.

Cheers
Thomas 🍔

**Comment by thomas-ziirsen** [comment]
Code has been commitet and a new version of the extension is available on the market place - v.1.0.3

Happy coding.

Cheers
Thomas 🍡
